README.md, apps/admin/src/App.tsx, apps/admin/src/shared/kyInstance.ts, apps/shop/src/shared/fetcher.ts, mocks/orders.json, mocks/orders_fail.json
- 논의된 응답 구조에 따라 응답 구조를 변경함
- 백오피스 요청시 path만 보내도록 수정
- readme 수정
=> chore: API 응답 래퍼 2차 수정

apps/shop/app/order/[orderId]/page.tsx, apps/shop/app/page.tsx, apps/shop/next.config.ts
=> [안성민] 주문 상세 페이지 UI 추가

apps/shop/src/features/main/components/product/Badge.tsx, apps/shop/src/features/main/components/product/BannerCard.tsx, apps/shop/src/features/main/components/product/ProductCard.tsx, apps/shop/src/features/main/components/product/ProductGrid.tsx, apps/shop/src/shared/shadcn.ts
모바일과 데스크탑에서 UI 수정 관련 작업을 진행하였습니다.
뱃지는 UI는 수정하여 다른 화면에서 사용하여도 좋지만 기획에 없어서 일단은 빼두었습니다.
=> feat: 상품 컴포넌트 UI 수정

apps/shop/app/order/[orderId]/page.tsx, apps/shop/app/order/page.tsx, apps/shop/app/page.tsx, apps/shop/app/product/[id]/page.tsx, apps/shop/app/product/page.tsx, apps/shop/src/features/main/components/product/ProductCard.tsx, apps/shop/src/features/order/OrderHistoryList.tsx, apps/shop/src/features/order/OrderHistoryPage.tsx, apps/shop/src/features/order/api/orderApi.ts, apps/shop/src/features/order/components/OrderHeader.tsx, apps/shop/src/features/order/components/OrderInfo.tsx, apps/shop/src/features/order/components/OrderProduct.tsx, apps/shop/src/features/order/components/PaymentInfo.tsx, apps/shop/src/features/order/components/ShippingInfo.tsx, apps/shop/src/features/order/components/index.ts, apps/shop/src/features/order/mocks/orderDetailMock.ts, apps/shop/src/features/order/mocks/orderHistoryMock.ts, apps/shop/src/features/product/components/ProductInfo.tsx, apps/shop/src/features/product/components/RecommendedProducts.tsx, apps/shop/src/features/review/components/CreateReviewModal.tsx, apps/shop/src/shared/components/shared/Icon.tsx, apps/shop/src/shared/utils/formatUtils.ts
=> [안성민] 주문내역 리스트 추가, 주문내역/주문상세 목데이터 분리

apps/shop/src/features/cart/icons/Cancel.tsx, apps/shop/src/features/cart/icons/Delete.tsx, apps/shop/src/features/product/components/AddCartPopup.tsx
SVG 컴포넌트에 대한 import가 누락되었습니다. IDE에서 따로 에러가 표시되지 않아 그냥 머지됐었는데 수정하였습니다. (아래 표시한 아이콘입니다)
=> fix: svg 컴포넌트 잘못 불러오는 문제 수정

apps/shop/app/mypage/page.tsx, apps/shop/src/features/mypage/components/LinkedMenu.tsx, apps/shop/src/features/mypage/components/ShippingProductInfo.tsx, apps/shop/src/features/mypage/components/UserInfo.tsx, apps/shop/src/features/mypage/icons/MoreIcon.tsx
마이페이지의 메뉴들은 클릭하면 다른 페이지나 팝업이 표시된다고 생각하고 작업하였습니다.
=> feat: 마이페이지 UI 추가

apps/shop/src/features/cart/components/Summary.tsx, apps/shop/src/features/product/components/AddCartPopup.tsx, apps/shop/src/features/product/components/RecommendedProducts.tsx, apps/shop/src/features/search/search-component.tsx, apps/shop/src/shared/utils/api.ts
결제 페이지 링크 연결
장바구니 문구 수정
안쓰는 로직 제거
검색결과 장바구니 담기 버튼 연동 (영상 시나리오: 검색 결과 페이지에서 장바구니로 이동)
목데이터 기본 반환
=> [안성민] 시연 영상 촬영 관련 추가 작업 

apps/shop/app/page.tsx, apps/shop/app/review/page.tsx, apps/shop/app/reviews/[productId]/page.tsx, apps/shop/next.config.ts, apps/shop/src/features/product/components/ProductPage.tsx, apps/shop/src/features/product/components/ProductReviews.tsx, apps/shop/src/features/reviews/components/ReviewCard.tsx, apps/shop/src/features/reviews/components/ReviewList.tsx, apps/shop/src/features/userReview/api/userReviewApi.ts, apps/shop/src/features/userReview/components/UserReviewCard.tsx, apps/shop/src/features/userReview/components/UserReviewList.tsx, apps/shop/src/features/userReview/mocks/userReviewMock.ts, apps/shop/src/features/userReview/types/index.ts, apps/shop/src/shared/components/ui/StarRating.tsx
상품상세 페이지의 리뷰 우측 상단에 붙어있는 > 버튼과 연결해둔 상태입니다.
위에서 > 버튼 누르면 여기로 이동합니다
=> [안성민] 리뷰 관리 리스트 UI

README.md, package.json
타이핑을 줄이기 위해 추가해보았습니다.
쇼핑몰 프로젝트 실행
`pnpm --filter shop dev`
`pnpm dev:shop`
백오피스 프로젝트 실행
`pnpm --filter admin dev`
`pnpm dev:admin`
쇼핑몰 애플리케이션 빌드
`pnpm build:shop`
백오피스 애플리케이션 빌드
`pnpm build:admin`
모든 애플리케이션 빌드
`pnpm build:all`
=> feat: 명령어 추가

apps/shop/app/review/create/page.tsx, apps/shop/src/features/order/components/OrderCheckoutPage.tsx, apps/shop/src/features/order/components/PaymentSummary.tsx, apps/shop/src/features/product/api/productApi.ts, apps/shop/src/features/product/mocks/productMock.ts, apps/shop/src/features/product/types/index.ts
현재 dev -> main 머지 시 빌드 오류 수정한 부분입니다.
=> fix: 타입 관련 오류 수정

apps/shop/app/review/create/page.tsx, apps/shop/src/features/order/components/OrderCheckoutPage.tsx, apps/shop/src/features/order/components/PaymentSummary.tsx, apps/shop/src/features/product/api/productApi.ts, apps/shop/src/features/product/components/ProductQuantity.tsx, apps/shop/src/features/product/mocks/productMock.ts, apps/shop/src/features/product/types/index.ts
input이 너무 버튼과 비슷하게 생겼다는 리더님의 지적이 있어 변경하였습니다.
=> chore: 상품 상세 수량 선택 컴포넌트 UI 변경

apps/shop/app/main/page.tsx, apps/shop/src/features/main/components/HeroBanner.tsx, apps/shop/src/shared/components/layout/Header.tsx
변경 전 / 변경후 (1)
<br/>
<br/>
<br/>
<br/>
<br/>
-----
변경 전 / 변경 후 (2)
=> [안성민] 공통 헤더의 태그 부분 제거

apps/admin/src/index.css, apps/admin/src/pages/products/Products.tsx, apps/admin/src/shared/components/ui/pagination/Pagination.tsx, apps/admin/src/shared/components/ui/pagination/index.ts
=> feat: 백오피스 페이지네이션 컴포넌트 추가

apps/shop/package.json, apps/shop/src/features/main/components/HeroBanner.tsx, pnpm-lock.yaml
https://github.com/user-attachments/assets/369fbeb2-11a2-43f9-b9db-1c69384cf0dc
짜투리 시간에 간단한 효과를 넣어보았습니다
=> feat: 메인에 스크램블 효과 추가

apps/shop/src/features/myReviews/components/MyReviewList.tsx, apps/shop/src/features/order/components/OrderProduct.tsx, apps/shop/src/features/reviewCreate/components/CreateReviewModal.tsx
- 리뷰 수정도 넣을까 하다가 수정 넣으려면 백엔드에서 이전 리뷰데이터를 줘야하는데 매우 번거로워져서 그냥 리뷰 작성하면 버튼을 disabled 시켰습니다.
- 마이페이지에서 리뷰 삭제가 요청됐는데 팝업은 사라지지 않는 문제 수정
=> feat: 주문 상세 페이지에서 리뷰 작성 버튼 추가

apps/shop/src/features/order/components/OrderHistoryList.tsx, apps/shop/src/features/order/types/index.ts, apps/shop/src/features/order/types/orderListItem.ts, apps/shop/src/shared/utils/getOrderStatusLabel.ts
* fix: 주문 준비 수정
* fix: 결제 준비
* fix: 기타 수정
* chore: 주문목록 임시커밋
* feat: 주문내역 조회 쿼리 추가
* feat: 주문내역 필터 적용
* fix: 주문내역 목록 링크 수정
* 주문내역 필터 수정
* 주문내역 페이지 제목 위치 수정
* 반품 버튼 삭제
* 취소/교환/환불내역 링크버튼 주석처리
* 결제 완료후 라우팅 경로 수정
* 빌드 에러 수정
* 배송지 관리 페이지 변경버튼 조건부렌더링 처리
* 배송 준비중 상태 추가
* 배송조회 버튼 수정
---------
=> Feat/hbs/order (#136)

apps/shop/app/product/[id]/page.tsx, apps/shop/app/review/create/page.tsx, apps/shop/src/features/cart/components/CartProduct.tsx, apps/shop/src/features/cart/components/Item.tsx, apps/shop/src/features/cart/components/QuantityChange.tsx, apps/shop/src/features/cart/components/Summary.tsx, apps/shop/src/features/cart/hooks/useCart.ts, apps/shop/src/features/product/api/productApi.ts, apps/shop/src/features/product/components/AddCartPopup.tsx, apps/shop/src/features/product/components/ProductInfo.tsx, apps/shop/src/features/product/components/ProductQuantity.tsx, apps/shop/src/features/product/types/index.ts
- 장바구니 수량 선택이 1슬리브 단위라는 것을 명확히 하기 위해 UI를 전체적으로 수정
- 장바구니 수량 변경에 디바운스 적용하여 수량 변경이 빨리 일어나지 않는 문제 수정
- 장바구니 삭제 api 변경된것에 맞춰 수정
- 상품 상세 페이지 타이틀을 상품 이름으로 수정
=> chore: 장바구니 관련 편의성 수정

apps/shop/app/layout.tsx, apps/shop/app/main/page.tsx, apps/shop/app/mypage/page.tsx, apps/shop/src/features/mypage/components/EditUserInfo.tsx, apps/shop/src/features/mypage/components/UserInfo.tsx, apps/shop/src/features/mypage/components/user/UserPopup.tsx
=> feat: 마이페이지 유저 닉네임 조회 및 변경 기능 추가

apps/shop/src/features/product/components/AddCartPopup.tsx, apps/shop/src/features/product/components/AddToCart.tsx, apps/shop/src/shared/components/layout/Header.tsx, apps/shop/src/shared/components/shared/ConfirmDialog.tsx
=> chore: 로그인 안되어있을때 장바구니 담기 버튼 클릭시 alert 추가

apps/shop/src/features/main/components/PromotionalContent.tsx
=> chore: 커피레터 문구 수정

apps/shop/src/features/order/components/OrderProduct.tsx, apps/shop/src/features/order/types/orderDetail.ts
주문 상세 페이지에서 리뷰 작성 요청시 productId 안들어가는 문제 및 상품 클릭시 1번 아이템으로만 이동하는 문제 수정
=> fix: 주문 상세 페이지 오류 수정

apps/shop/app/api/auth/[...nextauth]/route.ts, apps/shop/app/api/users/addresses/[addressId]/route.ts, apps/shop/app/api/users/addresses/route.ts, apps/shop/next.config.ts
This reverts commit 531b6da5ead7c84d8f470ce6671f4bb024947174.
=> Revert "fix: 보안 및 URL 관련 설정 수정 - next.config.ts, route.js"
